language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - /^(?i:release)-.+$/
  
addons:
  sonarcloud:
    organization: "komposten-github"
    token: $SONAR_TOKEN
    
before_install:
 - chmod +x gradlew
    
script:
  - ./gradlew check
  - ./gradlew sonarqube
